# This file is part of the dune-gdt project:
#   http://users.dune-project.org/projects/dune-gdt
# Copyright holders: Felix Albrecht
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)

Module: dune-gdt
Version: 0.2
Maintainer: felix.albrecht@uni-muenster.de
Depends: dune-common (>= 2.2) dune-grid-multiscale (>= 0.1) dune-stuff (>= 2.2) dune-fem (>= 1.3) dune-fem-localfunctions
Suggests: dune-pdelab
