# ~~~
# This file is part of the dune-gdt project:
#   https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt
# Copyright 2010-2021 dune-gdt developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2010 - 2014, 2016 - 2018)
#   Martin Drohmann (2011)
#   Martin Nolte    (2011)
#   René Fritze     (2016, 2018)
#   Tobias Leibner  (2018 - 2019, 2021)
# ~~~

Module: dune-gdt
Version: 2021.1.3
Maintainer: felix.schindler@wwu.de
Depends: dune-localfunctions (>= 2.6) dune-xt (>= 2021.1)
