# This file is part of the dune-gdt project:
#   https://github.com/dune-community/dune-gdt
# Copyright 2010-2017 dune-gdt developers and contributors. All rights reserved.
# License: Dual licensed as  BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2010 - 2014, 2016 - 2017)
#   Martin Drohmann (2011)
#   Martin Nolte    (2011)
#   Rene Milk       (2016)

Module: dune-gdt
Version: 0.2
Maintainer: felix.schindler@wwu.de
Depends: dune-common (>= 2.4) dune-xt-grid dune-xt-la dune-xt-functions
Suggests: dune-fem (>= 1.3) dune-pdelab dune-grid-multiscale dune-alugrid
